### ISSUE TITLE
Radix v2 Proof of Concept

### ISSUE THREAD

**Issue by StephenHaney** [modulz/radix#115]
Typescript
styled-system
Theme spec

Starting with a few components as a PoC.

**Comment by peduarte** [comment]
PoC lives here: https://github.com/modulz/radix-poc

Some thoughts around using styled-system variants: https://spectrum.chat/styled-system/general/dealing-with-multiple-variants~b808556e-80e9-4c8e-be3f-dde9ae186c44

**Comment by colmtuite** [comment]
I checked out the new Radix POC. I love the overall direction we're going—it's gonna be so great. Just wanna get a discussion started here. I'm gonna keep this brief, just so we have somewhere to begin.

Here are my thoughts/concerns so far:

- Does this use Brent's new theming standardisation spec? I haven't looked into it much yet.
- I don't understand why styled-system allows just one variant. The way I look at dumb UI components, most of them have many variants. Extending a base component to add a variant like `MediumButton` has never made sense to me. The size is a variant of the default component, so shouldn't it be architected that way? The same goes for color, state etc.
- I know Brent likes to allow users to change the fontSize of a component by passing a prop. Adam Morse, John Otander, Diana Mounter and all of their crew seem to be aligned on this. It's something I've always disagreed strongly with. The way I see it, a component's styles should be defined by a designer and then locked down. Alternatives should be encapsulated in variants. But devs should not be able to just override styles on the fly. (besides spacing etc. of course)
- I think the size scale naming convention (small, medium, large) is a mistake. I assume we will need to fight to the death about this? :)
- Do you @peduarte prefer "primary", "error", "warning" type color names? I think anything other than "blue", "green", "red" etc. is a mistake. Also anticipating a death match here too!
- We need to consider whether we use "theme.js" or "tokens.js". Jina-Anne coined the term "Design Tokens" at Salesforce. They have an elaborate library called Theo built around it. She's huge in the design system space and I think using "Tokens" could help us with adoption/marketing. I don't care about it at all besides that point.

An additional thought from a business perspective:

- I think we should drop Storybook. I know Storybook would help us, but a huge part of our roadmap is a Storybook competitor. In the next 6 months, we need to make a start at replicating Storybook and improving upon it. I'll write more about this in the docs tech spike thread.

The main idea behind all of this:

We've gone back and forth on all of this Radix stuff a lot over the past couple months. I haven't really communicated my thoughts well anywhere. So here's the plan.

Radix is just our design system, for building Modulz. It's not that important, relative to the core product. But the long-term play is so much bigger than that.

Modulz exports code. Nothing special, many tools do that. But not a single tool that exports code has been adopted by the dev community. Most investors and founders I chat to think this is because the code export is not good enough. That's incorrect. The reason is that the code export doesn't leverage the libraries that the developer community utilise.

If we're going to stand ANY chance of getting the dev community to adopt the code Modulz outputs, we need to achieve two things:

- Our output HAS to be built on top of the code libraries that the community uses—styled-system, Tailwind, Tachyons, Bootstrap etc.
- Our own design system (Radix) HAS to be built with Modulz.

So, my primary hope here, is that we move away from worrying about our own problems (DX, moving Radix into core etc.) and try to take a more holistic approach. What we're working on here will of course become Radix v2, but it will also lay the foundations for Modulz code export.

I thought that was going to be brief.

**Comment by peduarte** [comment]
@colmtuite Thanks for your thoughts. I'll address your questions/concerns below

---

> Does this use Brent's new theming standardisation spec? I haven't looked into it much yet.

More or less. There are a few things in the spec that I'm not sure we're following correctly, but it could be due to our implementation detail.
For example: The current Radix Button has a [fixed height](https://github.com/modulz/radix/blob/develop/src/components/Button.js#L29) which is derived from [Radix's spacing scale](https://github.com/modulz/radix/blob/fded180861637563caeee9f98550e4665223db1c/src/theme/Spacing.js). However Styled System [Theme Spec has a height property](https://styled-system.com/theme-specification#key-reference), which is supposed to be used for heights. *But* I don't think the height theme key is supposed to be used for button heights - this seems weird to me. I also think it's weird to have the button's height being determined from a spacing scale. So I'd probably give it a line-height and some vertical padding (from the space scale) until we reach the desired height. So to answer your question, I am following the theme spec as much as possible but for now I haven't changed any of the CSS for Radix, so there may be a couple of places that's not as per the spec. Easily solvable though.

---

> I don't understand why styled-system allows just one variant. The way I look at dumb UI components, most of them have many variants. Extending a base component to add a variant like MediumButton has never made sense to me. The size is a variant of the default component, so shouldn't it be architected that way? The same goes for color, state etc.

I've dug deeper into this, and Styled Components allows you to create custom Variants using [their API](https://styled-system.com/api#variant). So we could create a custom `size` variant for the `Button` Component 👍 Adopting this approach would mean we don't need to create components such as `MediumButton`.

---

> I know Brent likes to allow users to change the fontSize of a component by passing a prop. Adam Morse, John Otander, Diana Mounter and all of their crew seem to be aligned on this. It's something I've always disagreed strongly with. The way I see it, a component's styles should be defined by a designer and then locked down. Alternatives should be encapsulated in variants. But devs should not be able to just override styles on the fly. (besides spacing etc. of course)

This is completely up to us. If we don't want to expose `fontSize` we don't have to. I definitely see your point, and once again we have control over how much flexibility vs constraints we want to allow. I think there are certain benefits to exposing `fontSize` to certain components, such as `Text` Primitive (so long as the allowed values are from the theme).

---

> I think the size scale naming convention (small, medium, large) is a mistake. I assume we will need to fight to the death about this? :)

Are you proposing that we use `size1`, `size2` etc? I don't think there's right or wrong, as long as it's documented in the Design System. I'd rather we didn't fight *to death* over this 😂everyting is refactor-able later on.

---

> Do you prefer "primary", "error", "warning" type color names? I think anything other than "blue", "green", "red" etc. is a mistake. Also anticipating a death match here too!

I usually go for "primary", "danger", type of naming convention, they make sense when you have interchangeable themes. For example: a "danger" variant could use the `red` value on a light theme and `orange` on a dark theme. If we go with names such as "blue", "red" etc, then when the theme changes, we also need to change the CSS values to use a different key from the theme - otherwise it could get complicated! 

---

> We need to consider whether we use "theme.js" or "tokens.js". Jina-Anne coined the term "Design Tokens" at Salesforce. They have an elaborate library called Theo built around it. She's huge in the design system space and I think using "Tokens" could help us with adoption/marketing. I don't care about it at all besides that point.

Brent's spec uses Theme. I think it's the way to go. I could be wrong but I always thought that a Theme is a collection of Tokens. To me, a token is as simple as `red: #ff0000`. But you know more about this than I do!

---

> I think we should drop Storybook. I know Storybook would help us, but a huge part of our roadmap is a Storybook competitor. In the next 6 months, we need to make a start at replicating Storybook and improving upon it. I'll write more about this in the docs tech spike thread.

Makes sense 👍 I'll replace it with something else.

---

I also agree with the idea behind Radix. The more I work with Styled System the more I think it could potentially simplify the code export - it probably means we won't have to write the CSS properties ourselves, we could literally rely on Styled System (even if we need CSS properties that are not included, since they export the [Style function API](https://styled-system.com/api#style)), but I'm too familiar with how that's done atm, so it'd be goop to get @StephenHaney and the rest of the team's feedback on that.

If we can do this, when it comes to building Radix *with* Modulz, we'll be sure that it's totally doable.

**Comment by StephenHaney** [comment]
> I usually go for "primary", "danger", type of naming convention, they make sense when you have interchangeable themes. For example: a "danger" variant could use the red value on a light theme and orange on a dark theme. 

Colm already knows this, but I'm a proponent of this approach as well (as someone who's often had to deal with multiple brands using the same code). Is there a reason not to have both?

> Our own design system (Radix) HAS to be built with Modulz.

This idea has been confusing us a bit - Radix has state and logic, Modulz doesn't design state or logic, thus how can Radix be built entirely with Modulz?

Colm and I chatted on this and I get it more now – really, we need to figure out the best practice workflow for how Modulz exports get used in real, logical apps. And the best way to do that is dogfood Radix. How DO we go about using Modulz exports in Radix logical components ASAP? This idea is so important, it is deserving of its own thread. TBC.

> Code Export

The rendering code uses pure CSS classes as any type of CSS-in-JS solution has a performance tax (comes into play when dragging the opacity slider around, for instance).

Since we need to export to many different libraries, the data model and exporting code is agnostic.

Modulz currently thinks of Components this way: each Component is made up of Variants (and 'base' is considered a Variant too)... each Variant has its own set of states (normal, hover, etc)... Each state has a set of properties... those property values can be Theme references, strings, bools, or rows (for properties that allow multiple values like box-shadow).

This data model covers "the good parts" of the CSS spec. For instance, you can't do descendant selectors, but we consider them to be a bad practice in a good Component architecture.

From the data model, we write parsers that transform it into any library or style (we have the basics for Styled Components and plain HTML/CSS in a BEM-ish style now).

**Comment by colmtuite** [comment]
The other we need to consider is light/dark/auto mode. This is something we'll need to implement before August, preferably sooner.

I have more thoughts on it, but figured I should just mention it now rather than wasting a day waiting for more time.

Any thoughts on what the best way to handle that is?

**Comment by peduarte** [comment]
Hey 👋 

I've done a write about my PoC findings here: https://www.notion.so/modulz/Radix-PoC-d7dd57ef27b74324aa5e81cef31d7b07

So far my focus has been around Component Architecture and API design.

Once we have decided which approach we want to move ahead with, I will:
- Answer any questions you may have
- Raise any questions to Brent, if needed
- Build a few more complex Components
- Think about how we can split the state from Components that rely on it
- Add Typescript

/cc @colmtuite @StephenHaney @hadihallak @loklaan 

👊

**Comment by loklaan** [comment]
@peduarte Great write up! Small detail but I love the switch to serif in notion on that page haha.

I couple questions came to mind as I was reading and exploring:

1. At the moment all the examples are referencing the theme statically, how would you change it to be referenced dynamically?  
  _e.g. `styled-components` has its `ThemeProvider`, would you want to use that?_
2. All of the `styled-system` token getters are functions - without having dived further into it, will we run into the same (interpolations -> css comparisons) performance issues as whats currently observed in Radix?
3. Also perf wise, would `styled-systems` work without `styled-components`, in case we have to drop `styled-components` due to performance limitations?

**Comment by loklaan** [comment]
@colmtuite 

> I think we should drop Storybook. I know Storybook would help us, but a huge part of our roadmap is a Storybook competitor.

I'm a (fairly inactive) Storybook team member, so we're technicality competing with ourselves hahaha. Also polite reminder that these GH issues and comments are public; Radix is a public repo.

But to address the quote, I think Storybook is great for internal use for obvious reasons of iteration speed and great presentation, and I think we'd be premature in dropping it _now_ without further rational.

> I haven't really communicated my thoughts well anywhere. So here's the plan.

Yaaaas, _puts on reading glasses._

> ... The reason is that the code export doesn't leverage the libraries that the developer community utilise.

I'm in agreeance here! Well atleast:  
**"doesn't leverage the libraries that the developer ~community~ utilises"**

A team should have granular control over what the exports are, which isn't impossible with other tools that do static exports but they do make you jump through hurdles. 

> If we're going to stand ANY chance of getting the dev community to adopt the code Modulz outputs...

> What we're working on here will of course become Radix v2, but it will also lay the foundations for Modulz code export.

The priciples here are misaligned and maybe coming from a technical misunderstanding. 😬

As @StephenHaney mentions above, the way code exports are done in Modulz is agnostic to any community library (including Radix).

_The design of Radix won't drive how code exports are done._

How code exports are done probably _should_ drive how Radix is designed though, to push us to dogfood on the Modulz design->export cycle.

This rational of pushing ourselves to dogfood our own product as soon as possible is why I've been pushing for Radix to solve our own problems first, but also in the open to satisfy marketing strategies, such as exploring `styled-system` in the open which was amazing to witness. If v1 and v2 Radix eventually gets replaced in v3 by the exports of Modulz, then I imagine we're going to look back and wish we'd helped ourselves a bit more by keeping the Radix development cycle closer to it's core use (modulz core).

**Comment by peduarte** [comment]
@loklaan Thanks for these questions 🙌 

> At the moment all the examples are referencing the theme statically, how would you change it to be referenced dynamically?
e.g. styled-components has its ThemeProvider, would you want to use that?

This is open for debate. There's a few different approaches for this, which are:
1. Set the `theme` as a default prop of each component - this is good because it makes the usage simpler, just import a Component from Radix and you're good to go
2. Radix exports the `theme`, and it's up to the user to apply the `theme` via `ThemeProvider` - I'm not sure this is the recommended way, as we'd probably want our theme to be baked into every component by default. The `ThemeProvider` is useful if the user wants to override the Theme from the design system or if you're building your own UI which is not distributed. 
3. Radix exports a `BaseStyled` Component, which is "mandatory" that the user wraps the whole application in it. We can then set global styles if needed and use `ThemeProvider` internally.
I haven't spent time going deep into those options yet, since it's more React-y than Styled System-y 😆 

> All of the styled-system token getters are functions - without having dived further into it, will we run into the same (interpolations -> css comparisons) performance issues as whats currently observed in Radix?

I haven't ran any perf audit on this, but `themeGet` function is recommended because it safe guards from missing values - it's also nice that supports a fallback value. So, if we're doing a theme look up by key ourselves, for example `color: ${theme.colors.red}` and then later we refactor `red` to ` danger`, we'd get a JS error.


>Also perf wise, would styled-systems work without styled-components, in case we have to drop styled-components due to performance limitations?

We can use Styled System with Styled Components or Emotion, it's not optimised to be used without any of those. Although, it's **technically possible** - I've created this [CodeSandbox demo](https://codesandbox.io/s/v035q8440y) for you.

**Comment by loklaan** [comment]
> We can use Styled System with most other css-in-js libraries

Oh thank you thank you, this is brilliant and opens up what we can do with it! I also tried [jamming a theme in there to good result](https://codesandbox.io/s/jz7n9zkow). Promising.

> I'm not sure this is the recommended way, as we'd probably want our theme to be baked into every component by default.

<p align="center"><img src="https://media.giphy.com/media/3o85xIO33l7RlmLR4I/giphy.gif" /></p>

I'm all for an easy default, but that shouldn't get in the way of extensibly!

For example:

1. "Night" mode would be very easy to accomplish if we can swap the `theme` out for the whole app at once (React context saves-the-day, eg `ThemeProvider`).
1. We may want to change the theme for a particular chunk of the App, say for example if we wanted to show a "blocking" dialog and theme it to also emphasis color in a particular way that might be "offbrand" - or even switch it to Night mode in isolation.

To that end I'm keen for your 3. suggestion, some kind of `BaseStyle` (or `RadixThemeProvider` to borrow semantics?).

```js
/* With the default Radix theme. */
const App = (
  <RadixThemeProvider>
    ...
  </RadixThemeProvider>
)

/* With a custom theme. */
import { themes } from 'radix-ds'
const customTheme = { ...themes.default, colors: myCustomColors };
const App = (
  <RadixThemeProvider theme={customTheme}>
    ...
  </RadixThemeProvider>
)

/* Bonus: we ship a "default" night theme */
import { themes } from 'radix-ds'
const App = (
  <RadixThemeProvider theme={themes.dark}>
    ...
  </RadixThemeProvider>
)
```

> `themeGet` function is recommended because it safe guards from missing values

That part is good, we should definitely carry that. The perf issue I was bringing up though is how `styled-components` will go down it's [(very) "slow-path"](https://github.com/styled-components/styled-components/blob/df2c947e0a2a61e739b391cd8a47a787a56f6f5b/packages/styled-components/src/models/StyledComponent.js#L228) when it encounters a function value returned on any of the expressions found in tpl string interpolations. Probably not worth addressing until you get around to perf audit (ping me when ya do, I'll give a braindump on what I already for this stuff which I hope will save time and energy).

**Comment by peduarte** [comment]
I'm gonna close this as I think we all agree this is no longer a "Proof of Concept" 😄
