### ISSUE TITLE
Primitives repository mdlz-prmtz

### ISSUE THREAD

**Issue by potty** [modulz/radix#160]
Hey, I'm using just standalone Radix System, but I'd like to see, how the primitives are implemented without installing the whole radix package. Is there a reason why it's a private repo?

**Comment by peduarte** [comment]
Hey @potty 👋 

Thanks for reaching out. I hope Radix System is working well for you. Please keep in mind we're heavily working on all Radix related packages and they're all in alpha at the moment, so semver versioning hasn't even started properly. Although I don't foresee any big breaking changes happening in Radix System since it's so low-level.

Styled System v5.1.0 implemented a new Variant API which is inspired by Radix System's, you can see here: https://styled-system.com/variants/

So I'm now considering whether to keep it or remove it from our library. Just a heads up.

Now back to your questions 😅 

> I'd like to see, how the primitives are implemented without installing the whole radix package.

Just to clarify, Radix and the Modulz Primitives are separate things. Radix _consumes_ the Primitives and adds its own look and feel onto them. If you just want to see how Radix is customising the Primitives, you don't need to install Radix, you can browse some of the Components on Github, like the [Slider](https://github.com/modulz/radix/blob/master/packages/radix/src/components/Slider.tsx)

> Is there a reason why it's a private repo?

Yes, this is still quite new and not ready to be publicised, we published it to NPM so we could dogfood it. So far it's working really well, but I wouldn't recommend using it yet. Everything will probably change in the next few months :)

Thanks so much for your interest in these libraries, let me know if you have any more questions.

Cheers!

**Comment by potty** [comment]
Thanks for your response! I'm asking because I'm building my custom primitives and wanted to get some inspiration from Radix ones. Currently, I'm using primitives that were part of this repo some time ago, but maybe it would be nice if I could use just the Radix primitives directly in my project to build components on it. :)

I like the Variant API and I think the question is similar to whether you are going to reexport `css` function from styled-system. I don't know how well-typed is `variant` on styled-system side, but I would keep it consistent and leave it on styled-system side if possible.

Also, I have a question about component props. I have some Box component https://jsfiddle.net/pL6e9k1a/ . Suggestions for props works fine, but not prop values, also prop values are not type-checked. No dealbreaker, but would be really nice. So my question is whether I'm doing something wrong or it's how it works currently.

If there is anything I can help you with, especially with strongly typed styled-system/Radix components, just let me know! Really appreciate your work on this whole thing!

**Comment by peduarte** [comment]
@potty hey!  Sorry for the delay, we were busy preparing and attending Clarity conference.

As of Styled System v5.1.0, the `variant` API has ben updated to be aligned with the one from Radix.

Right now I'm considering whether to remove it completely from Radix and just rely on SS's one, but I need to run some tests first.

https://github.com/styled-system/styled-system/blob/master/CHANGELOG.md#v510-2019-08-12

Regarding TS, @jxnblk is considering re-writing Styled System in Typescript, if this goes ahead, it'll be much better than what I'm currently doing, which is adding Types later on.

Before I commit to invest a bunch of more time making it 100% TS compatible, I'm gonna wait for Jackson to make a decision.

However, if you see anything that could be improved please feel free to contribute!

Cheers

**Comment by destructobeam** [comment]
Sorry if I am hijacking a little, but I am looking at/playing around with making a Svelte port of Radix if that is okay, and it seems like a lot of the reset styles are also contained in the primitives package unless I am missing something?

Would it be possible to make that respository public or add individuals to the repo with read permissions?

Thanks!

**Comment by peduarte** [comment]
@destructobeam Hey, sounds like an interesting experiment! I've been wanting to try Svelte for a while, but haven't had a chance yet.

Radix is currently built on top of a different Library, which is heavily WIP. This is all part of how [Modulz](https://modulz.app) will work - so at this time it's not possible to make that library public. 

Feel free to borrow the Radix Theme and general look and feel and re-build it with Svelte, though! 

Thanks 👊

**Comment by destructobeam** [comment]
@peduarte Cheers, I am still fairly new to Svelte, but absolutely love it so far, especially with Sapper.

Was using Radix with React for an admin app and really dig the clean, minimalist aesthetic. I’m early enough on in that project that I thought combining the two would be cool.

Understand about not wanting to make those internals public. If there is an easy way to export/copy/paste the reset styles in to a gist or something that would make my day, but if that’s a pain I will grab them out of web inspector.

Thanks again!

**Comment by peduarte** [comment]
I'd suggest grabbing them out of the inspector for now. I can't share anything that's happening in that package just yet.

Thanks so much! 👊
