### ISSUE TITLE
Scrolling while Popover is open will make the page scroll after it's closed

### ISSUE THREAD

**Issue by hadihallak** [modulz/radix#165]
![Popover-scroll](https://user-images.githubusercontent.com/13556017/64127397-8cbc2200-cdc2-11e9-91fe-1e67ebef90fd.gif)

### Steps to reproduce: 
1. Open Popover
2. Scroll the page
3. Close the Popover by clicking anywhere on the page

### Expected behavior:
The page should not scroll back

### Actual behavior:
The page will sometimes scroll back.

Noticed that this might be relative to how far I scroll (as seen in the gif, if you scroll just a tiny bit then the page won't scroll)

BTW, some design systems block scrolling while a popover is open, not sure if we should do the same. keen to hear your thoughts

**Comment by StephenHaney** [comment]
This is because the popover returns focus to the previously focused item after it closes (an accessibility feature).

I wonder if we should consider using
```
element.focus({
  preventScroll: true
});
```
for this return focus.

**Comment by hadihallak** [comment]
Yeah, I agree 👍 either prevent scroll on focus or disable scrolling altogether when a popover is open.

**Comment by peduarte** [comment]
Thanks for this @hadihallak 


Like @StephenHaney mentioned, this is an accessibility feature. I agree that it could be an unwelcome surprise for most users though.

> BTW, some design systems block scrolling while a popover is open, not sure if we should do the same. keen to hear your thoughts
We had implemented like this initially, but after some conversations with @colmtuite we've decided against it.

@StephenHaney I didn't even know you could pass `preventScroll` to the `focus` API, that's good to know! 

I think that's a decent solution, however this logic lives in [react-focus-on](https://github.com/theKashey/react-focus-on)

I just checked it on [caniuse](https://caniuse.com/#feat=mdn-api_htmlelement_focus_preventscroll_option) and the support is not great, but I guess it's still a fine since it's more like an enhancement. What do you think?

**Comment by StephenHaney** [comment]
Yeah, it's supported in Edge, Chrome, and FireFox... just not in Safari (though they're working on it). Since it's part of the standard spec, it should eventually work everywhere.

react-focus-on looks to be actively maintained - maybe we can request it as a feature? Or open a PR to them with the implementation.

**Comment by peduarte** [comment]
Yeah we can definitely contribute to that project 👍 

Will get on this tomorrow. Thanks for the suggestion <3

**Comment by benoitgrelard** [comment]
Yeah I've already gotten several PRs merged on react-focus-on so it should be fine. I'll look at this today. 👍

**Comment by peduarte** [comment]
Fixed. PR created in https://github.com/modulz/modulz/pull/26
