### ISSUE TITLE
Cursor: text

### ISSUE THREAD

**Issue by StephenHaney** [modulz/radix#188]
From @colmtuite 
> Inputs and textareas on marketing screens, auth screens and general app UI (hardcore product UIs can be special-cased) should have cursor: text.

**Comment by peduarte** [comment]
I think the inputs in the App are better when the cursor is default instead of text. It gives it that native feel, which I think is appropriate.

We can approach this in a few different ways:
1. Introduce a variant which controls the cursor type
2. Have all the inputs with `cursor:text`
3. Override this behaviour globally from the App Global CSS

@colmtuite Do you have any preference?

I think if we think we'll have a few components that need a special treatment in the app environment, we could go with option 1 and make this variant consistent across all said components. Could be a variant named `uiType` which could be `website` or `webapp`. We can choose to default to the one where Radix will be used the most.

Just throwing some ideas out there.

Any thoughts?

/cc @benoitgrelard @vladmoroz

**Comment by vladmoroz** [comment]
@peduarte I personally like the variant option, it's the cleanest and achieves what we want to do. Other options don't spark joy to me 🤔 

Another suggestion: we'll be looking soon into a specialised editor input component of sorts – the one that presumably handles arrow keys, selection on focus, discard on Escape, all this stuff that is specific to cool apps for _real proz™_. We can handle it from there, be it custom styles just for that component or a variant.

**Comment by colmtuite** [comment]
Option #2 is definitely off the table for me. Most of the inputs need to function normally, it's just a really weird experience when there's no affordance. That's not how inputs on the web work generally.

Option #1 works for me. I agree with Vlad that the variant should be called `cursor`. I'm not a fan of abstracting these things, I like keeping things explicit/obvious wherever possible.

I agree with Vlad's suggestion of waiting. I think the best approach here is to have a different component, which composes `Input` and overrides its `cursor` style.

**Comment by peduarte** [comment]
Maybe option 2 was worded wrong, I meant to say that, we remove `cursor: default` from the Radix Input. 

If Modulz wants to override the cursor, it can be done at the App level.

This way, there are no variants, and we have a common cursor for Inputs.

**Comment by colmtuite** [comment]
But we need both `cursor: text` and `cursor: default` in Modulz. Most inputs should behave normally, some inputs in the editor should use `cursor: text`.

Is that possible with what you're suggesting above?
