### ISSUE TITLE
[Select] Scroll lock

### ISSUE THREAD

**Issue by raunofreiberg** [modulz/radix#263]
Hey 👋

While playing around with the [demo of Select](https://www.modulz.app/blog/under-the-spotlight-select), I noticed a small disparity between the native and custom Select.

The custom Select does not lock the scroll of the window when open, whereas the native one does.

I guess this can be a deliberate choice on your end to diverge from the native implementation, but I just thought I'd point it out.

![gif](https://gyazo.com/ea81b3afa1f0c6c5d8a81d09c88618fb.gif)

✌️

**Comment by peduarte** [comment]
Hey! 👋 

The demo is rendered in an `iframe` that's why the top-level page is still scrollable. This doesn't happen on the native select because the native menu gets rendered above everything (including browser frame). That's something that's not possible for us to do though :/

Hope that makes sense!

**Comment by raunofreiberg** [comment]
That makes sense!

I guess you could emulate the native behavior by canceling wheel events on the window when the select is open. Though, you would then have to consider that the select can be inside a scrollable container and deal with that as well.

Most of the higher quality selects I've seen don't disable scrolling either. And it might be just me, but I actually prefer it that way 😅

Feel free to close this. Thanks for the reply!

**Comment by peduarte** [comment]
Glad it makes sense, thanks for raising it! 👊
