### ISSUE TITLE
Theming doesn't seem to work

### ISSUE THREAD

**Issue by kartiknair** [modulz/radix#272]
Hey there I was trying to use this in a Next.js project & I passed the `<RadixProvider>` a custom theme but it only works for some components. For example the `<p>` tags will have the font family I specified however a `<Button>` wont.

Is this an issue on my end or something else?

**Comment by peduarte** [comment]
Hey hey

Im surprised that it works for *some* components. It shouldn't work for any, that's by design 😄 

Radix is Modulz's design system. It's not supposed to be themable. For that, you may want to consider something like Theme UI, Reakit, Tailwind.

Radix itself, is built with Modulz. So instead of using the alternative I mentioned above, you'll be able to use modulz to visually design, maintain and deploy your own design system.

Sorry for the confusion.

**Comment by kartiknair** [comment]
Ah sorry about the misunderstanding & thanks for the clarification 👍

**Comment by peduarte** [comment]
No worries! Thanks for raising an issue 🙌
